base_url = "https://thoughtexpo.com"
title = "thoughtexpo"
description = "@leelavg's corner on the internet"
compile_sass = true
author = "Leela Venkaiah G"

taxonomies = [
  {name = "tags"},
]

[markdown]
render_emoji = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
    { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
]

[extra]
links = [
  {name = "home", url = "@/_index.md"},
  {name = "posts", url = "@/posts/_index.md"},
]
goat_counter = "leelavg"
